version: '3'

services:
  api-solid-pg:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Leer2025
          POSTGRES_DB: PjaSistarefas
