version: '3'

services:
    app1: &app
        build: .
        hostname: app1
        expose:
          - "8082"
        depends_on:
          - api-solid-pg
        environment:
          DATABASE_CLIENT: 'postgresql'
          DATABASE_URL: 'postgres://postgres:abc.123@pi_mobile:5432/find-a-friend'
          ACCESS_TOKEN: 'e65f48ed7cc165fbd26b8d4caa08303b'
        ulimits:
          nproc: 1000000
          nofile:
            soft: 1000000
            hard: 1000000
        command: npm run start
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: '0.6GB'
    app2:
      <<: *app
      hostname: app2
  
    api-solid-pg:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Leer2025
        POSTGRES_DB: PjaSistarefas
      deploy:
        resources:
          limits:
            cpus: '0.4'
            memory: '1.5GB'
    nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app1
        - app2
      ports:
        - "3333:3333"
      ulimits:
          nproc: 1000000
          nofile:
            soft: 1000000
            hard: 1000000
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: '0.3GB'