version: '3'

services:
    app1: &app
        build: .
        hostname: app1
        expose:
          - "8082"
        ports:
          - 8082
        depends_on:
          - sistarefas
        environment:
          DATABASE_CLIENT: 'postgresql'
          DATABASE_URL: 'postgres://postgres:Leer2025@sistarefas:5432/PJASisTarefas'
          ACCESS_TOKEN: 'e65f48ed7cc165fbd26b8d4caa08303b'
        ulimits:
          nproc: 1000000
          nofile:
            soft: 1000000
            hard: 1000000
        command: npm run start
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: '0.6GB'
    app2:
      <<: *app
      hostname: app2
  
    sistarefas:
      container_name: sistarefas
      image: postgres:14-alpine
      ports:
        - 3339:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Leer2025
        POSTGRES_DB: PJASisTarefas
      deploy:
        resources:
          limits:
            cpus: '0.4'
            memory: '1.5GB'
            
    nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app1
        - app2
      ports:
        - "3333:3333"
      ulimits:
          nproc: 1000000
          nofile:
            soft: 1000000
            hard: 1000000
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: '0.3GB'